module.exports = {
  // Normal log actions
  TYPE_ADVANCEMENT: "completed_advancement",
  TYPE_CHALLENGE: "completed_challenge",
  TYPE_GOAL: "completed_goal",
  TYPE_CHAT: "chat",
  TYPE_LOGIN: "login",
  TYPE_LOGOFF: "logoff",
  TYPE_COMMAND: "command",
  TYPE_SERVERINFO: "serverinfo",
  TYPE_SERVERREADY: "serverready",
  TYPE_SERVERSTOP: "serverstop",
  TYPE_PLAYERUUID: "player_uuid",
  SEV_INFO: "sev_info",
  SEV_WARN: "sev_warn",
  SEV_ERROR: "sev_error",
  TYPE_ERROR: "type_error",
  TYPE_OVERLOADED: "type_overloaded",
  TYPE_KEEPENTITY: "type_keepentity",

  // Cause of death codes
  ARROW_DEATH: "death_arrow",
  CACTUS_DEATH: "death_cactus",
  WATER_DEATH: "death_water",
  ELYTRA_DEATH: "death_elytra",
  EXPLOSION_DEATH: "death_explosion",
  FALLING_DEATH: "death_falling",
  ANVIL_DEATH: "death_anvil",
  FIRE_DEATH: "death_fire",
  FIREWORK_DEATH: "death_firework",
  LAVA_DEATH: "death_lava",
  LIGHTNING_DEATH: "death_lightning",
  MAGMA_DEATH: "death_magma",
  KILLED_DEATH: "death_killed",
  FIREBALL_DEATH: "death_fireball",
  POITION_DEATH: "death_potion",
  STARVE_DEATH: "death_starve",
  SUFFOCATE_DEATH: "death_suffocate",
  THORNS_DEATH: "death_thorns",
  VOID_DEATH: "death_void",
  WITHER_DEATH: "death_withered",
  BLUDGEON_DEATH: "death_bludgeon",
};
